jobs:
  pull_request:
    uses: Nullus157/.github/.github/workflows/pull_request.yml@main
  readme:
    uses: ./.github/workflows/readme.yml
  success:
    runs-on: ubuntu-latest
    needs: [pull_request, readme]
    steps:
    - run: true

on:
  pull_request:
    branches: [main]
