jobs:
  pull_request:
    uses: Nullus157/.github/.github/workflows/pull_request.yml@main
  readme:
    uses: ./.github/workflows/readme.yml
  success:
    runs-on: ubuntu-latest
    needs: [pull_request, readme]
    if: ${{ always() }}
    steps:
    - if: ${{ contains(needs.*.result, 'failure')  }}
      run: exit 1
    - if: ${{ contains(needs.*.result, 'cancelled')  }}
      run: exit 1
    - if: ${{ contains(needs.*.result, 'skipped')  }}
      run: exit 1

on:
  pull_request:
    branches: [main]
