jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y ripgrep
    - run: |
        expected="$(script -q -c 'sh -c "stty cols 80 && cargo run -q -- dl --help"' $(mktemp) | sed -E -e 's/\x1b\[[0-9;]*m//g' -e 's/\r//g' -e 's/ *$//')"
        echo "$expected"
        rg -FUq "$expected" README.md

on:
  workflow_call:
